System integration test
RaaLabs/IdentityMapper pull request #13
Opened 2021-03-22 14:25 UTC by srudaa

2021-04-08 19:23 UTC, rafaelschlatter commented
Nice documentation! This would definitely be helpful on all modules & connectors. Ill add to the ones im working on.

2021-04-09 09:50 UTC, thotokraa requested changes
Please fix the issues commented, plus the code coverage warnings.

2021-04-09 09:50 UTC, thotokraa commented on Source/IdentityMapper.csproj
> +    <PackageReference Include="RaaLabs.Edge" Version="1.0.1" />
The latest version is 1.0.4. Please update.

2021-04-09 09:50 UTC, thotokraa commented on Source/IdentityMapperHandler.cs
> +    [ExcludeFromCodeCoverage] // Tested in system integration test
This handler should be tested, now that we have solved how to do that.

2021-04-09 09:50 UTC, thotokraa commented on Specifications/Features/SystemIntegration.Specs.feature
> +    Put feature description here
Not really that descriptive :P

2021-04-09 09:50 UTC, thotokraa commented on Specifications/Steps/Steps.cs
>   *  Licensed under the MIT License. See LICENSE in the project root for license information.
This class needs a better, more descriptive name. I suggest TimeSeriesMapperSteps.

2021-04-09 09:50 UTC, thotokraa commented on Specifications/Steps/TagMappingSteps.cs
>  {
I can't see that this class is being used in a .feature file. Can it be removed?

2021-04-16 14:49 UTC, thotokraa approved these changes

2021-04-16 19:34 UTC, merged