Tagregistry change
RaaLabs/IdentityMapper pull request #24
Opened 2021-11-17 12:42 UTC by maikberthelsen

## Summary

Added possibility to receive metadata as a dictionary from connectors. Sends one event to the Prioritizer, and one event to the TagRegistry, containing additional fields.

### Added

- The field MetaData in the incoming event may contain a dictionary. A new outgoing event is included, which goes to the TagRegistry. This event includes the source and the tagname, and the Metadata. All events are forwarded to the TagRegistry, whether it is mapped in the identities file or not.

### Changed

-  new route to the TagRegistry is added, the path to the Prioritizer is kept the same as before.

2021-11-22 14:56 UTC, rafaelschlatter reviewed
Looks good. Some minor comments. Lets also wait for Thomas review before merging.

2021-11-22 14:56 UTC, rafaelschlatter commented on Source/events/EdgeHubDataPointWithSource.cs
> +        #nullable enable
What does this annotation do?

2021-11-22 14:56 UTC, rafaelschlatter commented on Specifications/Steps/TagMappingSteps.cs
>  using BoDi;
Does this package need to be referenced in `Specifications/IdentityMapper.Specs.csproj`?

2021-11-23 09:53 UTC, maikberthelsen commented on Source/events/EdgeHubDataPointWithSource.cs
> +        #nullable enable
It removed the warning for using nullable types. But not sure if it is the correct way.

2021-11-23 09:55 UTC, maikberthelsen commented on Specifications/Steps/TagMappingSteps.cs
>  using BoDi;
Yes, I just changed the order of them

2021-11-25 12:29 UTC, thotokraa requested changes
Looks good for the most part, but I want some minor changes done before you merge.

2021-11-25 12:29 UTC, thotokraa commented on Source/events/EdgeHubDataPointWithSource.cs
> +        #nullable enable
You could also add #nullable to the start of the file, which would look a bit nicer.

2021-11-25 12:29 UTC, thotokraa commented on Source/events/EdgeHubDataPointReceived.cs
> +        #nullable enable
Like in EdgeHubDataPointWithSource: put this at the top of the file instead.

2021-11-25 12:29 UTC, thotokraa commented on Source/IdentityMapperHandler.cs
> +                if (e is MissingTagInSourceException || e is MissingSourceException)
What is going on here? If the source is missing from the event, then create a new variable containing the same data as before and retransmit?

2021-11-25 12:29 UTC, thotokraa commented on Specifications/Drivers/EdgeHubDataPointWithSourceVerifier.cs
> +            var source = row["Source"];
Can this variable be removed?

2021-11-25 12:29 UTC, thotokraa commented on Specifications/Steps/TagMappingSteps.cs
>  using BoDi;
No, we don't need to reference this package in the csproj file, because it is received through SpecFlow.

2021-11-26 09:44 UTC, maikberthelsen commented on Source/IdentityMapperHandler.cs
> +                if (e is MissingTagInSourceException || e is MissingSourceException)
The source is not missing from the tag, the source is not specified in identities.json. So if I have not mapped any NMEA data in the identities file I still want them to be sendt to the TagRegistry to show that they are present, so the event is sent to the TagRegistry only.

2021-11-26 09:51 UTC, maikberthelsen commented on Source/events/EdgeHubDataPointWithSource.cs
> +        #nullable enable
If I move it to the top then it complains at the dynamic variable.
Non-nullable property 'Value' must contain a non-null value when exiting constructor. Consider declaring the property as nullable. [IdentityMapper]

2021-11-26 09:51 UTC, maikberthelsen commented on Specifications/Steps/TagMappingSteps.cs
>  using BoDi;
Sorry I misunderstood the question. Does anything need to be changed?

2022-01-05 20:35 UTC, srudaa commented
@thotokraa could we merge this PR?

2022-01-14 12:13 UTC, thotokraa approved these changes

2022-01-17 06:54 UTC, merged